# Generated by Django 4.1.2 on 2022-10-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapedgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=63)),
                ('away', models.CharField(max_length=63)),
                ('currentScore', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=300)),
            ],
        ),
    ]
